services:
  collapse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collapse
    ports:
      - "8000:8000"
    volumes:
      - ./backend/storage:/app/storage
    restart: unless-stopped
